name: File Action
on:
  push:
    branches:
      - main

jobs:
  file-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create or Delete file
        run: |
          # Comando para crear un archivo
          echo "Este es un archivo de prueba" > new_file.txt

          # Comando para borrar un archivo
          rm new_file.txt

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update files"
